aliases:
  chats:
    - alias: botgroup
      chatid: -1001787389818
    - alias: testgroup
      chatid: -1001787389818
  emails:
    - alias: DevOps CI
      address: CAB-SA-CI001104@sberbank.ru
    - alias: DevTools
      address: devtools@nsedov.com 
  