aliases:
  chats:
    - alias: groupchat
      chatid: -1001223595847
      caption: true
    - alias: groupchat-prompt
      chatid: -1001223595847
      caption: false
    - alias: testgroup
      chatid: -1001787389818
      caption: true
    - alias: testgroup-prompt
      chatid: -1001787389818
      caption: false
  emails:
    - alias: Jenkins
      address: CAB-SA-CI001104@sberbank.ru
    - alias: DevTools
      address: devtools@nsedov.com
content:
  replace:
    - pattern: УВЕДОМЛЕНИЕ О КОНФИДЕНЦИАЛЬНОСТИ[^<]+
      replacement:
# Calendar of scheduled events
events:
  once:
    # Release-20230325
    - moment: 2023-03-06T09:30:00+03:00
      messageRef: hello.all
      destination: groupchat-prompt
    - moment: 2023-03-06T09:30:05+03:00
      messageRef: notification.before.ift
      messageArgs: Release-20230325
      destination: groupchat-prompt
    - moment: 2023-03-07T09:30:00+03:00
      messageRef: morning.all
      destination: groupchat-prompt
    - moment: 2023-03-07T09:30:05+03:00
      messageRef: notification.due.ift
      messageArgs: Release-20230325
      destination: groupchat-prompt
    - moment: 2023-03-08T10:30:00+03:00
      messageRef: greetings.march8
      destination: groupchat-prompt
    - moment: 2023-03-13T09:30:00+03:00
      messageRef: notification.before.psi
      messageArgs: Release-20230325
      destination: groupchat-prompt
    - moment: 2023-03-14T09:30:00+03:00
      messageRef: notification.due.psi
      messageArgs: Release-20230325
      destination: groupchat-prompt
    # Release-20230422
    - moment: 2023-04-03T09:30:00+03:00
      messageRef: notification.before.ift
      messageArgs: Release-20230422
      destination: groupchat-prompt
    - moment: 2023-04-04T09:30:00+03:00
      messageRef: notification.due.ift
      messageArgs: Release-20230422
      destination: groupchat-prompt
    - moment: 2023-04-10T09:30:00+03:00
      messageRef: notification.before.psi
      messageArgs: Release-20230422
      destination: groupchat-prompt
    - moment: 2023-04-11T09:30:00+03:00
      messageRef: notification.due.psi
      messageArgs: Release-20230422
      destination: groupchat-prompt
    # Release-20230527
    - moment: 2023-05-09T09:30:00+03:00
      messageRef: notification.before.ift
      messageArgs: Release-20230527
      destination: groupchat-prompt
    - moment: 2023-05-10T09:30:00+03:00
      messageRef: notification.due.ift
      messageArgs: Release-20230527
      destination: groupchat-prompt
    - moment: 2023-05-15T09:30:00+03:00
      messageRef: notification.before.psi
      messageArgs: Release-20230527
      destination: groupchat-prompt
    - moment: 2023-05-16T09:30:00+03:00
      messageRef: notification.due.psi
      messageArgs: Release-20230527
      destination: groupchat-prompt
messages:
  - id: about.me
    text: Я - чат-бот SberConnect. Создан на базе ChatGPT - большой языковой модели, разработанной компанией OpenAI. Я обучен понимать и генерировать естественный язык, чтобы помогать людям в получении ответов на их вопросы и решении задач. Я могу отвечать на различные вопросы, давать советы и предоставлять информацию по различным темам.
  - id: about.groupchat.details
    text: В групповом чате со мной можно пообщаться, набрав текст сообщения после команды /chat. Например, /chat Что такое искусственный интеллект?.
  - id: about.privatechat.details
    text: Можно написать мне лично (@sbconn_bot), тогда можно обойтись без команды /chat в начале сообщения.
  - id: about.draw.details
    text: Можно попросить меня нарисовать картинку по текстовому описанию с помощью команды /draw. Например, /draw Танцующий робот.
  - id: morning.all
    text: Всем доброго утра!
  - id: hello.all
    text: Всем приветы в этом чате!
  - id: notification.before.ift
    text: Напоминалка от меня, что завтра начинается ИФТ релиза %s
  - id: notification.due.ift
    text: Как я уже говорил, сегодня начинаем ИФТ релиза %s
  - id: notification.before.psi
    text: Всем привет! Завтра начинается ПСИ релиза %s
  - id: notification.due.psi
    text: Как дела? Начинаем ПСИ релиза %s!
  - id: greetings.march8
    text: С праздником, девчонки! Тусить с вами в этом чатике - сплошное удовольствие! 💐🥂