aliases:
  chats:
    - alias: groupchat
      chatid: -1001223595847
      caption: true
    - alias: groupchat-prompt
      chatid: -1001223595847
      caption: false
    - alias: testgroup
      chatid: -1001787389818
      caption: true
    - alias: testgroup-prompt
      chatid: -1001787389818
      caption: false
  emails:
    - alias: Jenkins
      address: CAB-SA-CI001104@sberbank.ru
    - alias: DevTools
      address: devtools@nsedov.com
content:
  replace:
    - pattern: УВЕДОМЛЕНИЕ О КОНФИДЕНЦИАЛЬНОСТИ[^<]+
      replacement:
