aliases:
  chats:
    - alias: groupchat
      chatid: -1001223595847
      caption: true
    - alias: groupchat-prompt
      chatid: -1001223595847
      caption: false
    - alias: testgroup
      chatid: -1001787389818
      caption: true
    - alias: testgroup-prompt
      chatid: -1001787389818
      caption: false
  emails:
    - alias: Jenkins
      address: CAB-SA-CI001104@sberbank.ru
    - alias: DevTools
      address: devtools@nsedov.com
content:
  replace:
    - pattern: УВЕДОМЛЕНИЕ О КОНФИДЕНЦИАЛЬНОСТИ[^<]+
      replacement:
# Calendar of scheduled events
# Supported date&time formats https://go.dev/src/time/format.go
events:
  once:
    # Commons
    - moment: 2023-04-17T08:29:00+03:00
      promptRef: have.a.nice.day
      destination: groupchat-prompt
    - moment: 2023-04-17T08:31:00+03:00
      promptRef: current.date
      destination: groupchat-prompt
      messageArgs: 17 апреля

    # Release-20230527
    - moment: 2023-05-21T09:30:00+03:00
      promptRef: notification.before.ift
      messageArgs: завтра,Release-20230527
      destination: groupchat-prompt
    - moment: 2023-05-22T10:49:30+03:00
      promptRef: notification.due.ift
      messageArgs: Release-20230527
      doestination: groupchat-prompt
    - moment: 2023-05-26T16:08:00+03:00
      promptRef: notification.before.psi
      messageArgs: в понедельник,Release-20230527
      destination: groupchat-prompt
    - moment: 2023-05-29T09:30:00+03:00
      promptRef: notification.due.psi
      messageArgs: Release-20230527
      destination: groupchat-prompt

    # Release-20230617
    - moment: 2023-05-29T09:30:00+03:00
      promptRef: notification.before.ift
      messageArgs: завтра,Release-20230617
      destination: groupchat-prompt
    - moment: 2023-05-30T09:30:00+03:00
      promptRef: notification.due.ift
      messageArgs: Release-20230617
      destination: groupchat-prompt
    - moment: 2023-06-05T09:30:00+03:00
      promptRef: notification.before.psi
      messageArgs: завтра,Release-20230617
      destination: groupchat-prompt
    - moment: 2023-06-06T09:30:00+03:00
      promptRef: notification.due.psi
      messageArgs: Release-20230617
      destination: groupchat-prompt

    # Release-20230708
    - moment: 2023-06-19T09:30:00+03:00
      promptRef: notification.before.ift
      messageArgs: завтра,Release-20230708
      destination: groupchat-prompt
    - moment: 2023-06-20T09:30:00+03:00
      promptRef: notification.due.ift
      messageArgs: Release-20230708
      destination: groupchat-prompt
    - moment: 2023-06-26T09:30:00+03:00
      promptRef: notification.before.psi
      messageArgs: завтра,Release-20230708
      destination: groupchat-prompt
    - moment: 2023-06-27T09:30:00+03:00
      promptRef: notification.due.psi
      messageArgs: Release-20230708
      destination: groupchat-prompt

    - moment: 2023-05-26T16:59:00+03:00
      promptRef: imitate.speech
      messageArgs: пятница это лучший день недели, Тайлера Дерденна из фильма Бойцовский Клуб
      destination: groupchat-prompt

messages:
  - id: about.me
    text: Я - чат-бот SberConnect. Создан на базе ChatGPT - большой языковой модели, разработанной компанией OpenAI. Я обучен понимать и генерировать естественный язык, чтобы помогать людям в получении ответов на их вопросы и решении задач. Я могу отвечать на различные вопросы, давать советы и предоставлять информацию по различным темам.
  - id: about.groupchat.details
    text: В групповом чате со мной можно пообщаться, набрав текст сообщения после команды /chat. Например, /chat Что такое искусственный интеллект?.
  - id: about.privatechat.details
    text: Можно написать мне лично (@sbconn_bot), тогда можно обойтись без команды /chat в начале сообщения.
  - id: about.draw.details
    text: Можно попросить меня нарисовать картинку по текстовому описанию с помощью команды /draw. Например, /draw Танцующий робот.
  - id: errors.command.unsupported
    text: Команда %s не поддерживается
  - id: errors.command.argrequired
    text: Команда %s используется только совместно с текстом. Если вы выбираете команду из меню чата, вызывайте ее долгим нажатием, тогда будет возможность ввести текст перед отправкой.
  - id: errors.command.badresponse
    text: Не получилось сформировать ответ с помощью ChatGPT (возвращен HTTP-статус %d)

# Prompts are text queries sent to ChatGPT. The responses generated by ChatGPT are published by telegram bot in chats
prompts:
  - id: have.a.nice.day
    prompt: Напиши короткое пожелание хорошего дня для команды SberConnect
    altText: Всем хорошего дня! 
  - id: current.date
    prompt: Расскажи про интересный факт, связанный с датой %s
    altText: Хотел рассказать что-нибудь интересное про дату %s, но ничего не вспоминается 
  - id: notification.before.ift
    prompt: Напиши краткое сообщение команде SberConnect о том, что %s начинается стабилизация релиза SberConnect %s. В конце сообщи, что будет произведен выпуск дистрибутива и установка на стенд ИФТ.
    altText: Напоминалка от меня, что завтра начинается ИФТ релиза %s
  - id: notification.due.ift
    prompt: Напиши краткое сообщение команде SberConnect о том, что сегодня началось ИФТ релиза SberConnect %s.
    altText: Как я уже говорил, сегодня начинаем ИФТ релиза %s
  - id: notification.before.psi
    prompt: Напиши краткое сообщение команде SberConnect о том, что %s начинается ПСИ релиза SberConnect %s. В конце вырази надежду, что критичных дефектов в дистрибутиве на текущий момент не осталость.
    altText: Всем привет! Завтра начинается ПСИ релиза %s
  - id: notification.due.psi
    prompt: Напиши краткое сообщение команде SberConnect о том, что сегодня началось ПСИ релиза SberConnect %s.
    altText: Как дела? Начинаем ПСИ релиза %s!
  - id: best.wishes.for.psi
    prompt: Напиши пожелание успешного прохождения ПСИ релиза %s команде SberConnect
    altText: Желаю команде SberConnect успешного прохождения ПСИ релиза %s!
  - id: greetings.for.psi
    prompt: Напиши поздравления с успешным прохождения ПСИ релиза %s команде SberConnect, и поблагодари всех принимавших участие в подготовке релиза. В конце напиши для разработчиков, что будет произведено влитие релизной ветки в develop
    altText: Поздравляю команду SberConnect успешным прохождения ПСИ релиза %s!
  - id: happy.birthday
    prompt: Напиши поздравления %s с днем рождения от лица всей команды SberConnect
    altText: С днем рожнения, %s!
  - id: imitate.speech
    prompt: Напиши короткую речь о том, что %s. В ответе имитируй стиль речи %s
    altText: 