aliases:
  chats:
    - alias: groupchat
      chatid: -1001223595847
    - alias: testgroup
      chatid: -1001787389818
  emails:
    - alias: Jenkins
      address: CAB-SA-CI001104@sberbank.ru
    - alias: DevTools
      address: devtools@nsedov.com
schedule:
  once:
    - moment: 2023-02-22T00:12:20+03:00
      message: Do it once
      destination: testgroup